GENERATE_SEED: false
SEED: 475319212
ITERATIONS: 10000
TIME_STEP: 0.02
CUSTOM_COLORMAPS: false
PARTICLE_BLUR_CONFIGS:
  X_RADIUS: 1
  Y_RADIUS: 1
  DISTANCE: 0.01
  SCALE: 3
  WEIGHT_FORMULA: dist_sq
IMAGE_CONFIGS:
  WIDTH: 400
  HEIGHT: 400
  BACKGROUND_COLOR: black
  NAME: image
SHADER_CONFIGS:
  COLOR_MAP: RdGy
  REVERSED: false
  SPAN:
  - 20
  - 200
  HOW: eq_hist
SPREAD_CONFIGS:
  THRESHOLD: 0
  MAX_PX: 1
  SHAPE: circle
  HOW: add
FILTER_CONFIGS:
  GAUSSIAN:
    FILTER: false
    SIGMA_X: 1.5
    SIGMA_Y: 1.5
    TRUNCATE: 4
  MEDIAN:
    FILTER: false
    FOOTPRINT:
    - 3
    - 3
DENOISE_CONFIGS:
  TV:
    DENOISE: false
    WEIGHT: 0.1
    CHANNEL_AXIS: -1
  BILATERAL:
    DENOISE: false
    SIGMA_COLOR: 0.05
    SIGMA_SPATIAL: 15
    CHANNEL_AXIS: -1
FILE_CONFIGS:
  PATH: maps
  ID: 15
POINTS_CONFIGS:
  INIT_COORDS:
    X0: 0
    Y0: 0
    Z0: 0
  RADIUS: 2
  NUM_OF_POINTS: 100
STAGING_CONFIGS:
  KEEP_ASPECT_RATIO: false
  TYPE: ratio
  RATIO: 0.8
PERSPECTIVE_CONFIGS:
  X_ROTATION_DEG: 0
  Y_ROTATION_DEG: 0
  Z_ROTATION_DEG: 0
ATTRACTOR_CONFIGS:
  NAME: Clifford
  ARGS:
  - -1.4
  - -1.7
  - 1.3
  - -2.0
STARSCAPE_CONFIGS:
  DENSITY: 0