GENERATE_SEED: true
SEED: 1260523872
ITERATIONS: 500
TIME_STEP: 0.01
CUSTOM_COLORMAPS: true
PARTICLE_BLUR_CONFIGS:
  X_RADIUS: 2
  Y_RADIUS: 2
  DISTANCE: 0.01
  SCALE: 3
  WEIGHT_FORMULA: dist_sq
IMAGE_CONFIGS:
  WIDTH: 400
  HEIGHT: 400
  BACKGROUND_COLOR: black
  NAME: image
SHADER_CONFIGS:
  COLOR_MAP: kryptonite
  REVERSED: false
  SPAN:
  - 20
  - 200
  HOW: eq_hist
SPREAD_CONFIGS:
  THRESHOLD: 0
  MAX_PX: 1
  SHAPE: circle
  HOW: add
FILTER_CONFIGS:
  GAUSSIAN:
    FILTER: false
    SIGMA_X: 1.5
    SIGMA_Y: 1.5
    TRUNCATE: 4
  MEDIAN:
    FILTER: false
    FOOTPRINT:
    - 3
    - 3
DENOISE_CONFIGS:
  TV:
    DENOISE: false
    WEIGHT: 0.1
    CHANNEL_AXIS: -1
  BILATERAL:
    DENOISE: false
    SIGMA_COLOR: 0.05
    SIGMA_SPATIAL: 15
    CHANNEL_AXIS: -1
FILE_CONFIGS:
  PATH: maps
  ID: 8
POINTS_CONFIGS:
  INIT_COORDS:
    X0: 0
    Y0: 0
    Z0: 0
  RADIUS: 5
  NUM_OF_POINTS: 10000
PERSPECTIVE_CONFIGS:
  X_ROTATION_DEG: 0
  Y_ROTATION_DEG: 0
  Z_ROTATION_DEG: 0
ATTRACTOR_CONFIGS:
  NAME: TSUCS
  ARGS:
  - 39.19
  - 45.62
  - 0.29
  - 0.17
  - 0.74
  - 15.32
