"""Contains the loaded configs.yaml file as CONFIGS along with some shortcuts.

Written by Aaron Barge
Copyright 2022
"""


import random

import yaml


CONFIGS = {}

# Load configs
with open('configs.yml', 'r') as file:
    CONFIGS = yaml.safe_load(file)

# Generate seed
if CONFIGS["GENERATE_SEED"]:
    CONFIGS["GENERATE_SEED"] = False
    CONFIGS["SEED"] = random.randint(-2147483648, 2147483647)

# Seed RNG
random.seed(CONFIGS["SEED"])

# Create shortcuts
PARTICLE_BLUR_CONFIGS = CONFIGS["PARTICLE_BLUR_CONFIGS"]
IMAGE_CONFIGS = CONFIGS["IMAGE_CONFIGS"]
SHADER_CONFIGS = CONFIGS["SHADER_CONFIGS"]
SPREAD_CONFIGS = CONFIGS["SPREAD_CONFIGS"]
FILTER_CONFIGS = CONFIGS["FILTER_CONFIGS"]
GAUSSIAN_FILTER_CONFIGS = FILTER_CONFIGS["GAUSSIAN"]
MEDIAN_FILTER_CONFIGS = FILTER_CONFIGS["MEDIAN"]
DENOISE_CONFIGS = CONFIGS["DENOISE_CONFIGS"]
TV_DENOISE_CONFIGS = DENOISE_CONFIGS["TV"]
BILATERAL_DENOISE_CONFIGS = DENOISE_CONFIGS["BILATERAL"]
FILE_CONFIGS = CONFIGS["FILE_CONFIGS"]
POINTS_CONFIGS = CONFIGS["POINTS_CONFIGS"]
PERSPECTIVE_CONFIGS = CONFIGS["PERSPECTIVE_CONFIGS"]
ATTRACTOR_CONFIGS = CONFIGS["ATTRACTOR_CONFIGS"]
